[build]
  base = "frontend"
  publish = "build"
  functions = "../backend"

[functions."storeNewsToSupabase"]
  schedule = "0 * * * *" # Runs every hour

[functions."summarizeDailyNews"]
  schedule = "0 2 * * *" # Runs daily at 2AM UTC
