[build]
  base = "frontend"
  publish = "build"
  functions = "../backend"
  command = "npm ci --prefix .. && npm run --prefix .. test && npm run build"


[functions."summarizeDailyNews"]
  schedule = "0 2 * * *" # Runs daily at 2AM UTC
